name: Pipeline Teste CI/CI/CD

on:
  push:
    branches: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check repo
      uses: actions/checkout@v2
    
    - name: Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build image docker
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Install npm
      working-directory: ./teste-front
      run: npm install

    - name: Build npm
      working-directory: ./teste-front
      run: npm run build

    - name: Generate artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./teste-front/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist



      

